### ISSUE TITLE
Link-Error

### ISSUE THREAD

**Issue by chluknight** [deepflowio/docs#242]
The content of this link is not displaying properly.
https://deepflow.io/docs/zh/auto-metrics/metric-calc-desc/
1.1.1 吞吐量（Throuthput）
Field | DisplayName | Unit | Type | Description
-- | -- | -- | -- | --
generate from csv file: [vtap_app_port.ch?Category=Throuthput]

**Comment by ys-zhifu** [comment]
Word error
![image](https://user-images.githubusercontent.com/105471350/236606202-478288cc-0ef3-41ff-8edd-3a8ae3cd8fe3.png)

**Comment by ys-zhifu** [comment]
Display after repair
![image](https://user-images.githubusercontent.com/105471350/236607598-ae32c81e-f6f1-4fe3-8745-d68900514b8e.png)
